### ISSUE TITLE
ttime-windows-0.9.1 : cant load new data and chose courses (cant see anything )

### ISSUE THREAD

**Issue by hickmat** [lutzky/ttime#24]
would love if someone help

**Comment by lutzky** [comment]
Could you please paste any output from the terminal, and/or a screenshot?

**Comment by hickmat** [comment]
![untitled1](https://cloud.githubusercontent.com/assets/11507501/6673482/2071802e-cc1c-11e4-98d8-20d594088269.png)
![untitled2](https://cloud.githubusercontent.com/assets/11507501/6673481/206f7086-cc1c-11e4-8d08-5b6b4549b7a8.png)

**Comment by hickmat** [comment]
the second photo after uploading

**Comment by hickmat** [comment]
the second photo after updating data

**Comment by lutzky** [comment]
Looks like the REPY file format has been changed. REPY files used to be in IBM862/CP862 encoding, but not it seems that a strange new encoding is used - "a" for א, "b" for ב, "c" for ג, and so on. Very strange.

**Comment by lutzky** [comment]
I've taken a quick stab at this in 808552861024ebd83dcde0cd034526f8cffc5945, but that still crashes the parser (though output for `ttime --repy-utf8` now looks correct). They've probably changed more stuff :hankey:.

**Comment by hickmat** [comment]
I think it because they have changed the UG system , it will be ok

**Comment by boazg** [comment]
so this has been previously discussed here, with solutions and a fixed REPY file posted:
https://www.facebook.com/groups/cs.technion/permalink/856881521046522/

I think the problem here is more general and twofold:
1) We rely on the technion to publish correct data on time. The technion, in turn, throws obelisk. 
2) We cannot scrape UG/graduate from every computer, and even if we did have a scraper, we would still have to debug it each semester for new things the technion changes.

An example of a system that works is choiceFreak. They do number 2, and place ads in their app, so they are driven by capitalism. yay for capitalism. 

Another option is to be driven by student's will. This means allowing students to point ttime at any udonkey XML or REPY anyone publishes. maybe have a place that contains the current up-to-date data source. hand the keys to the local ASAT or something. 
adding a non-fixed URL is easy, and gadi already has a working parser for most things. 

This will require a new windows release.

**Comment by lutzky** [comment]
OK, Here's another crack at it - this version actually works, for Ruby 1.9. This will require additional testing for Ruby 1.8 (on which the Windows version is based), and also some work to make it compatible with the old format in case they switch back. @hickmat, could you try applying the following change to the code on your end and see if it magically works? 9f9e5e43db094bc052d1c79d9056eda343276e7d

**Comment by hickmat** [comment]
i am not a pro programmer but this what i have did 
![untitled234234](https://cloud.githubusercontent.com/assets/11507501/6683589/de49247a-cc90-11e4-960f-d5fa949dca55.png)

**Comment by KimiNewt** [comment]
I don't see the encoding.rb file in the Windows packaging. I'm guessing you have to rebuild it?

I have the same issue as above. Shouldn't have changed back from Ubuntu.

**Comment by lutzky** [comment]
Yes, but I don't have a Windows machine; in fact I wasn't the one who originally built the package, it was Boaz Goldstein. The package includes a Ruby distribution, which is gigantic. I mucked about with packaging it as a gem instead (3ceead4ab32962e08e26c9e89e1e5dc1bb759b27) for this exact reason - I'm more than happy to review pull requests... :wink:
As a workaround, you could perhaps drag encoding.rb from git straight into the extracted Windows package (in `lib/ttime`) and cross your fingers.
